server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #-addr: #localhost:8848 #配置Nacos地址
        server-addr: 192.168.79.128:1111  #ngix nacos 集群

management:
  endpoints:
    web:
      exposure:
        include: '*'


